version: 2.1
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - browser-tools/install-chrome:
          chrome-version: "123.0.6312.122"
          replace-existing: true
      - node/install-packages
      - run:
          name: UI Tests
          command: npm run uitest
          when: always
      - run:
          name: Start API Tests Server
          background: true
          command: |
            npm run dev 3000
            npx wait-on http://localhost:3000
          when: always
      - run:
          name: API Tests
          command: npm run apitest
          when: always
      - run:
          name: Stop API Tests Server
          background: true
          command: pkill -f "npm run dev 3000"
          when: always
workflows:
  e2e-test:
    jobs:
      - test
