version: 2.1
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - browser-tools/install-chrome:
          chrome-version: "123.0.6312.122"
          replace-existing: true
      - node/install-packages
      - run:
          command: npm run test
      - store_test_results:
          path: /tests_output
workflows:
  e2e-test:
    jobs:
      - test
